# Generated by Django 3.0.5 on 2020-08-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='./images')),
                ('prix', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
