# Generated by Django 3.0.5 on 2020-08-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieseshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('about', models.TextField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
