# Generated by Django 3.0.5 on 2020-08-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieseshop', '0003_auto_20200814_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
