# Generated by Django 3.0.5 on 2020-08-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieseshop', '0004_auto_20200814_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='prix',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
