# Generated by Django 3.0.5 on 2020-09-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieseshop', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='USD Order Total')),
                ('emailAddress', models.EmailField(blank=True, max_length=250, verbose_name='Email Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billingName', models.CharField(blank=250, max_length=250)),
                ('billingAddress1', models.CharField(blank=250, max_length=250)),
                ('billingCity', models.CharField(blank=250, max_length=250)),
                ('billingPostcode', models.CharField(blank=250, max_length=250)),
                ('billingCountry', models.CharField(blank=250, max_length=250)),
                ('ShippingName', models.CharField(blank=250, max_length=250)),
                ('ShippingAddress1', models.CharField(blank=250, max_length=250)),
                ('ShippingCity', models.CharField(blank=250, max_length=250)),
                ('ShippingPostcode', models.CharField(blank=250, max_length=250)),
                ('ShippingCountry', models.CharField(blank=250, max_length=250)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='USD price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieseshop.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
